- hosts: master
  gather_facts: true
  become: true
  tasks:
  - name: Add Kubernetes GPG key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - name: Add Kubernetes repository
    ansible.builtin.apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
  - name: Install packages
    ansible.builtin.package:
      name:
        - kubectl
      state: present
  - name: Check that the arkade exists
    stat:
      path: /usr/local/bin/arkade
    register: stat_result
  - name: Download Arkade
    ansible.builtin.uri:
      url: https://get.arkade.dev
      return_content: true
    register: arkade_installer
    when: not stat_result.stat.exists
  - name: Install Arkade
    ansible.builtin.shell:
      cmd: sh -s -- -y
      stdin: "{{ arkade_installer.content }}"
    when: not stat_result.stat.exists
  - name: Add Arkade to path
    become: true
    ansible.builtin.copy:
      dest: /etc/profile.d/custom-path.sh
      content: PATH=$PATH:/home/vagrant/.arkade/bin
      mode: 0776
  - name: Create folder .kube
    ansible.builtin.file:
      dest: /home/vagrant/.kube
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0700
  - name: Check k3s service exist
    ansible.builtin.service_facts:
  - name: Install k3s
    become: false
    ansible.builtin.shell:
      cmd: curl -sfL https://get.k3s.io | sh -
    when: services['k3s.service'] is not defined
  - name: Check k3s service exist
    ansible.builtin.service_facts:
  - name: Wait until node token is generated
    wait_for:
      path: /var/lib/rancher/k3s/server/node-token
    when: services['k3s.service'] is defined
  - name: Obtain token
    ansible.builtin.fetch:
      src: /var/lib/rancher/k3s/server/node-token
      dest: /tmp/node-token
      flat: yes
    when: services['k3s.service'] is defined
  - name: Get k3s conf
    ansible.builtin.fetch:
      src: /etc/rancher/k3s/k3s.yaml
      dest: /tmp/config
      flat: yes
  - name: Copy conf to .kube/config
    ansible.builtin.copy:
      src: /tmp/config
      dest: .kube/config
      mode: 0600
      group: vagrant
      owner: vagrant
